import 'package:cardnet/models/cardnet_response.dart';
import 'package:zencillo_helpers/zencillo_helpers.dart';

extension CardnetFormaPagoDetalleMapper on CardnetResponse {
  FormaPagoDetalleModel toFormaPagoDetalle({
    required int idTurno,
    required int numeroTurno,
    required int idDocument,
    required double total,
    required double taxTotal,
    required double subTotal,
    required int idFormaPago,
  }) {
    final result = FormaPagoDetalleModel(
      idVenta: idDocument,
      idTurno: idTurno,
      identificacionRed: 'CARDNET_POS',
      codigoRespuestaActor: '',
      mensajeRespuesta: data,
      secuencialTransaccion: int.tryParse(responseCode.toString()) ?? 0,
      numeroLote: numeroTurno,
      horaTransaccion: DateTime.now().getHourWindDev(),
      fechaTransaccion: DateTime.now(),
      numeroAutorizacion: autorizationCode.limit(10),
      tid: '',
      mid: autorizationCode.limit(10),
      valorInteres: 0,
      mensajeImpresion: '',
      codigoBanco: 0,
      nombreBanco: franchise,
      nombreGrupoTarjeta: franchise,
      modoLectura: '',
      nombreTarjetaHabiente: franchise,
      montoFijo: '',
      identificadorAplicacion: '',
      aid: '',
      tipoCrigtograma: '',
      pin: '',
      arqc: '',
      numeroTarjetaTruncado: lastFourDigitsCard,
      fechaVencimientoTarjeta: 0,
      numeroTarjetaEncriptada: lastFourDigitsCard,
      impuesto: taxTotal,
      baseConImpuesto: subTotal + taxTotal,
      baseSinImpuesto: subTotal,
      montoImpuesto: taxTotal,
      montoTotal: total,
      idFormaPago: idFormaPago,
      host: franchise,
      hostName: franchise,
      tipoTarjeta: franchise,
      tipoVenta: '',
      numeroTarjeta: lastFourDigitsCard,
      loteAbierto: '1',
      nombreTH: '',
      aprobacion: autorizationCode,
      idTerminal: '',
      numeroReferencia: responseCode.toString(),
      codigoReferencia: responseCode.toString(),
      idComercio: terminalId.toString(),
      diferidoyQuickPayment: '',
      reservado: '',
      archivoFirma: '',
      tvr: '',
      tsi: '',
      idCashBack: 0,
      anulada: false,
      multiplesVentas: false,
    );

    return result;
  }
}
